// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter echo carried back on every [`ConsolidationReportView`].
 * ADR-014 / phase13f §2.2 — handlers MUST surface what they actually
 * filtered against so the GUI never re-derives the active filter
 * from URL state alone.
 */
export type ConsolidationFilter = { 
/**
 * Repo allow-list after normalisation. Empty = no repo filter.
 */
repos: Array<string>, 
/**
 * Grain filter (`session` | `topic` | `decision_trace`). `None`
 * when no grain filter was applied.
 */
grain: string | null, };
