// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrainHealth } from "./GrainHealth";

/**
 * Top-level wire response for `/v1/health/consolidator`.
 */
export type ConsolidatorHealthReport = { 
/**
 * Session-grain status row.
 */
session_grain: GrainHealth, 
/**
 * Topic-grain status row.
 */
topic_grain: GrainHealth, 
/**
 * DecisionTrace-grain status row.
 */
decision_trace_grain: GrainHealth, };
