// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One row in the `/v1/health/freshness` table.
 */
export type FreshnessRow = { 
/**
 * Stage + kind/hook key (e.g. `adapter.publisher.tool_call`).
 */
key: string, 
/**
 * Most recent activity timestamp in Unix-epoch ms (`0` when the
 * stage has never emitted that signal).
 */
last_event_ts_ms: bigint, 
/**
 * Now - last_event_ts in whole seconds. `-1` when
 * `last_event_ts_ms == 0` so the GUI can render `—`.
 */
gap_seconds: bigint, 
/**
 * Bucket the GUI colour-codes on.
 */
severity: Severity, };
