// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-grain status row carried on the response.
 */
export type GrainHealth = { 
/**
 * `finished_at` stamp of the most recent
 * [`super::super::consolidator::ConsolidationReport`] row for
 * this grain. `None` when no run has been recorded yet.
 */
last_run: string | null, 
/**
 * Last status string (`success` / `failed` / `running`).
 * `None` when no run has been recorded.
 */
last_status: string | null, 
/**
 * Number of envelopes the last run emitted.
 */
envelopes_emitted: bigint, 
/**
 * Wall-clock latency of the last run in milliseconds.
 */
latency_ms: bigint, };
