// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14g §2.3 — per-pair intent mismatch row.
 */
export type IntentMismatchView = { 
/**
 * Intent the bundle was routed to.
 */
from: string, 
/**
 * Intent the operator corrected to (or the model's actual
 * intent inferred from feedback).
 */
to: string, 
/**
 * Total mismatch count for this `(from, to)` pair.
 */
count: bigint, };
