// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14f §4.3 — per-intent bundle-byte quantile row.
 */
export type IntentByteQuantilesView = { 
/**
 * Sample count.
 */
count: bigint, 
/**
 * 50th percentile (median bundle bytes for this intent).
 */
p50: number, 
/**
 * 95th percentile bundle bytes.
 */
p95: number, 
/**
 * 99th percentile bundle bytes.
 */
p99: number, };
