// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14f §4.3 — per-intent helpful-rate row driven by feedback
 * POSTs. `rate = helpful / (helpful + unhelpful)`; `None` when
 * no feedback has been recorded for this intent.
 */
export type IntentHelpfulRateView = { 
/**
 * helpful=true count.
 */
helpful: bigint, 
/**
 * helpful=false count.
 */
unhelpful: bigint, 
/**
 * `helpful / (helpful + unhelpful)`; serialised as `null`
 * when both halves are zero.
 */
rate: number | null, };
