// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntentByteQuantilesView } from "./IntentByteQuantilesView";
import type { IntentHelpfulRateView } from "./IntentHelpfulRateView";
import type { IntentMismatchView } from "./IntentMismatchView";

/**
 * Top-level wire response for `/v1/health/pre-thinking`.
 */
export type PreThinkingHealthReport = { 
/**
 * Current breaker state (`closed` / `open` / `halfopen`).
 */
breaker_state: string, 
/**
 * Failures observed in the current breaker window.
 */
failures_in_window: number, 
/**
 * Per-reason fail-open counts since process boot.
 */
fail_open_total: { [key in string]?: bigint }, 
/**
 * Sum across every reason — convenience field so the
 * dashboard can render a single counter.
 */
fail_open_sum: bigint, 
/**
 * Phase14f §4.1 — per-intent bundle-bytes quantiles. Empty
 * when no samples have been observed yet.
 */
bundle_bytes_per_intent: { [key in string]?: IntentByteQuantilesView }, 
/**
 * Phase14f §4.2 — per-intent helpful-rate counters.
 */
helpful_rate_per_intent: { [key in string]?: IntentHelpfulRateView }, 
/**
 * Phase14g §2.1 — `(from, to, count)` triples sorted by
 * count desc. Drives the `cortex-ops intent-stats` doctor
 * table.
 */
intent_mismatch_top: Array<IntentMismatchView>, 
/**
 * Phase14g §3.3 — per-path rewriter cascade counts. Paths:
 * `sonnet_hit`, `sonnet_cache_hit`, `sonnet_timeout`,
 * `sonnet_error`, `deterministic_fallback`.
 */
rewriter_path_total: { [key in string]?: bigint }, 
/**
 * phase26c §2.3 — bundle-cache hit count since adapter boot.
 */
cache_hit_total: bigint, 
/**
 * phase26c §2.3 — bundle-cache miss count since adapter boot.
 */
cache_miss_total: bigint, };
