// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntentByteQuantilesView } from "./IntentByteQuantilesView";
import type { IntentHelpfulRateView } from "./IntentHelpfulRateView";

/**
 * Top-level wire response for `/v1/health/pre-thinking`.
 */
export type PreThinkingHealthReport = { 
/**
 * Current breaker state (`closed` / `open` / `halfopen`).
 */
breaker_state: string, 
/**
 * Failures observed in the current breaker window.
 */
failures_in_window: number, 
/**
 * Per-reason fail-open counts since process boot.
 */
fail_open_total: { [key in string]?: bigint }, 
/**
 * Sum across every reason — convenience field so the
 * dashboard can render a single counter.
 */
fail_open_sum: bigint, 
/**
 * Phase14f §4.1 — per-intent bundle-bytes quantiles. Empty
 * when no samples have been observed yet.
 */
bundle_bytes_per_intent: { [key in string]?: IntentByteQuantilesView }, 
/**
 * Phase14f §4.2 — per-intent helpful-rate counters.
 */
helpful_rate_per_intent: { [key in string]?: IntentHelpfulRateView }, };
