// Auto-generated by scripts/generate-gui-types.sh — do not edit.
// Source of truth: Rust types with #[derive(ts_rs::TS)] under
// crates/cortex-api/. Regenerate after touching any of them and
// commit the diff (see phase14d / spec 26).

// ---- ConsolidationFilter.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter echo carried back on every [`ConsolidationReportView`].
 * ADR-014 / phase13f §2.2 — handlers MUST surface what they actually
 * filtered against so the GUI never re-derives the active filter
 * from URL state alone.
 */
export type ConsolidationFilter = { 
/**
 * Repo allow-list after normalisation. Empty = no repo filter.
 */
repos: Array<string>, 
/**
 * Grain filter (`session` | `topic` | `decision_trace`). `None`
 * when no grain filter was applied.
 */
grain: string | null, };

// ---- ConsolidatorHealthReport.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level wire response for `/v1/health/consolidator`.
 */
export type ConsolidatorHealthReport = { 
/**
 * Session-grain status row.
 */
session_grain: GrainHealth, 
/**
 * Topic-grain status row.
 */
topic_grain: GrainHealth, 
/**
 * DecisionTrace-grain status row.
 */
decision_trace_grain: GrainHealth, };

// ---- FreshnessRow.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `/v1/health/freshness` table.
 */
export type FreshnessRow = { 
/**
 * Stage + kind/hook key (e.g. `adapter.publisher.tool_call`).
 */
key: string, 
/**
 * Most recent activity timestamp in Unix-epoch ms (`0` when the
 * stage has never emitted that signal).
 */
last_event_ts_ms: bigint, 
/**
 * Now - last_event_ts in whole seconds. `-1` when
 * `last_event_ts_ms == 0` so the GUI can render `—`.
 */
gap_seconds: bigint, 
/**
 * Bucket the GUI colour-codes on.
 */
severity: Severity, };

// ---- GrainHealth.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-grain status row carried on the response.
 */
export type GrainHealth = { 
/**
 * `finished_at` stamp of the most recent
 * [`super::super::consolidator::ConsolidationReport`] row for
 * this grain. `None` when no run has been recorded yet.
 */
last_run: string | null, 
/**
 * Last status string (`success` / `failed` / `running`).
 * `None` when no run has been recorded.
 */
last_status: string | null, 
/**
 * Number of envelopes the last run emitted.
 */
envelopes_emitted: bigint, 
/**
 * Wall-clock latency of the last run in milliseconds.
 */
latency_ms: bigint, };

// ---- IntentByteQuantilesView.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14f §4.3 — per-intent bundle-byte quantile row.
 */
export type IntentByteQuantilesView = { 
/**
 * Sample count.
 */
count: bigint, 
/**
 * 50th percentile (median bundle bytes for this intent).
 */
p50: number, 
/**
 * 95th percentile bundle bytes.
 */
p95: number, 
/**
 * 99th percentile bundle bytes.
 */
p99: number, };

// ---- IntentHelpfulRateView.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14f §4.3 — per-intent helpful-rate row driven by feedback
 * POSTs. `rate = helpful / (helpful + unhelpful)`; `None` when
 * no feedback has been recorded for this intent.
 */
export type IntentHelpfulRateView = { 
/**
 * helpful=true count.
 */
helpful: bigint, 
/**
 * helpful=false count.
 */
unhelpful: bigint, 
/**
 * `helpful / (helpful + unhelpful)`; serialised as `null`
 * when both halves are zero.
 */
rate: number | null, };

// ---- IntentMismatchView.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase14g §2.3 — per-pair intent mismatch row.
 */
export type IntentMismatchView = { 
/**
 * Intent the bundle was routed to.
 */
from: string, 
/**
 * Intent the operator corrected to (or the model's actual
 * intent inferred from feedback).
 */
to: string, 
/**
 * Total mismatch count for this `(from, to)` pair.
 */
count: bigint, };

// ---- PreThinkingHealthReport.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level wire response for `/v1/health/pre-thinking`.
 */
export type PreThinkingHealthReport = { 
/**
 * Current breaker state (`closed` / `open` / `halfopen`).
 */
breaker_state: string, 
/**
 * Failures observed in the current breaker window.
 */
failures_in_window: number, 
/**
 * Per-reason fail-open counts since process boot.
 */
fail_open_total: { [key in string]?: bigint }, 
/**
 * Sum across every reason — convenience field so the
 * dashboard can render a single counter.
 */
fail_open_sum: bigint, 
/**
 * Phase14f §4.1 — per-intent bundle-bytes quantiles. Empty
 * when no samples have been observed yet.
 */
bundle_bytes_per_intent: { [key in string]?: IntentByteQuantilesView }, 
/**
 * Phase14f §4.2 — per-intent helpful-rate counters.
 */
helpful_rate_per_intent: { [key in string]?: IntentHelpfulRateView }, 
/**
 * Phase14g §2.1 — `(from, to, count)` triples sorted by
 * count desc. Drives the `cortex-ops intent-stats` doctor
 * table.
 */
intent_mismatch_top: Array<IntentMismatchView>, 
/**
 * Phase14g §3.3 — per-path rewriter cascade counts. Paths:
 * `sonnet_hit`, `sonnet_cache_hit`, `sonnet_timeout`,
 * `sonnet_error`, `deterministic_fallback`.
 */
rewriter_path_total: { [key in string]?: bigint }, };

// ---- Severity.ts ----
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity bucket the GUI colour-codes on.
 */
export type Severity = "ok" | "warn" | "critical";

