#!/usr/bin/env bash
# Phase14d — regenerate `gui/src/lib/api.generated.ts` from Rust
# wire types via `ts-rs`. Re-run after touching any type carrying
# `#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]` and
# commit the diff.
#
# CI mirrors this exact path; `pnpm -C gui run check-contract`
# fails the build when `git diff` against the regenerated bundle
# is non-empty.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TS_DIR="$REPO_ROOT/crates/gui-types"
TARGET="$REPO_ROOT/gui/src/lib/api.generated.ts"

cd "$REPO_ROOT"

# Strip every prior export so removed types do not linger as stale
# bindings.
rm -rf "$TS_DIR"

# Run the ts-rs export driver. The `#[cfg(feature = "ts-export")]`
# tests in cortex-api emit one .ts file per derived type into
# `$TS_DIR`. `cargo test` is the supported invocation per ts-rs
# v10; the driver is a no-op without the feature so the production
# `cargo test` cycle stays unaffected.
cargo test -p cortex-api --features ts-export --lib \
    ts_export::tests::ts_export_emits_every_registered_wire_type --quiet \
    >/dev/null

if [ ! -d "$TS_DIR" ]; then
    echo "error: ts-rs produced no output at $TS_DIR" >&2
    exit 1
fi

# Bundle every emitted .ts into a single api.generated.ts so the
# GUI gets one file to import and `git diff` operates on a single
# blob. Cross-file `import { X } from './Y'` references are
# stripped because everything ships in one module.
{
    echo "// Auto-generated by scripts/generate-gui-types.sh — do not edit."
    echo "// Source of truth: Rust types with #[derive(ts_rs::TS)] under"
    echo "// crates/cortex-api/. Regenerate after touching any of them and"
    echo "// commit the diff (see phase14d / spec 26)."
    echo
    for f in $(find "$TS_DIR" -name "*.ts" | sort); do
        echo "// ---- $(basename "$f") ----"
        # Drop cross-file imports — bundle is self-contained.
        grep -vE '^import type ' "$f"
        echo
    done
} > "$TARGET"

echo "wrote $TARGET ($(wc -l < "$TARGET") lines)"
