#!/usr/bin/env bash
# Keep `target/` from growing unbounded.
#
# Rust never garbage-collects build artifacts: stale object files,
# incremental caches, and rlibs from old dependency versions accumulate
# in `target/` forever until something removes them. Combined with the
# dev profile's debuginfo and the separate `release` + `llvm-cov-target`
# trees, that is how `target/` reached 500+ GB on this project.
#
# This script removes artifacts that have not been *accessed* in the last
# N days (default 14) — i.e. everything you are not actively building —
# while leaving the hot set intact, so the next build stays incremental.
#
# Usage:
#   scripts/sweep-target.sh                # sweep artifacts older than 14 days
#   scripts/sweep-target.sh 7              # ...older than 7 days
#   scripts/sweep-target.sh --dry-run      # preview only, delete nothing
#   scripts/sweep-target.sh 30 --dry-run   # combine
#
# One-time install of the underlying tool:
#   cargo install cargo-sweep
#
# For a hard reset that reclaims everything (forces a full rebuild next
# time) see the commands printed at the end, or run `cargo clean`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

DAYS=14
DRY_RUN=""
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN="--dry-run" ;;
        ''|*[!0-9]*) ;;            # ignore non-numeric (e.g. stray flags)
        *) DAYS="$arg" ;;
    esac
done

if ! command -v cargo-sweep >/dev/null 2>&1; then
    echo "error: cargo-sweep is not installed." >&2
    echo "       install it once with:  cargo install cargo-sweep" >&2
    exit 1
fi

echo "==> sweeping artifacts not accessed in the last ${DAYS} day(s) ${DRY_RUN:+(dry-run)}"
# Main workspace target/.
cargo sweep --time "$DAYS" $DRY_RUN .

# Coverage builds a separate instrumented tree (target/llvm-cov-target)
# that cargo-sweep's default pass does not touch. Drop it wholesale when
# not actively measuring coverage — it is regenerated by the next
# `cargo llvm-cov` run. Skipped in dry-run.
if [ -z "$DRY_RUN" ] && [ -d target/llvm-cov-target ]; then
    if command -v cargo-llvm-cov >/dev/null 2>&1; then
        echo "==> cleaning coverage tree (cargo llvm-cov clean --workspace)"
        cargo llvm-cov clean --workspace || true
    fi
fi

echo
echo "Done. To reclaim EVERYTHING (full rebuild next time), run instead:"
echo "    cargo clean                 # removes target/ entirely"
echo "    cargo clean --release       # release artifacts only"
echo "    cargo sweep --installed     # drop artifacts from uninstalled toolchains"
