//! Dashboard delta-event types (spec 21).
//!
//! Carried on the `cortex.events.dashboard` Synap stream and re-emitted
//! over `/v1/dashboard/stream` (SSE). One envelope shape covers every
//! mutation the dashboard cares about; the [`DashboardEventKind`] tag
//! discriminates the body. Mutations may originate from the MCP server
//! (a tool call wrote a file) or from the file-system watcher (a manual
//! edit landed). Consumers dedupe by `event_id` over a sliding window.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Wire envelope for one dashboard delta. Stable across MCP and watcher
/// publishers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DashboardEvent {
    /// ULID; generated by the publisher. Consumers dedupe by this.
    pub event_id: String,
    /// Tag selecting the body shape via `kind`.
    #[serde(flatten)]
    pub kind: DashboardEventKind,
    /// Entity affected by the change (task id, decision id, handoff
    /// filename, …). Shape is documented per kind in spec 21.
    pub entity_id: String,
    /// Optional human-readable one-liner. The GUI may surface it in a
    /// toast or activity feed; not a contract field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// RFC-3339 UTC timestamp set by the publisher.
    pub ts: String,
    /// Optional minimal patch describing the change. Shape is intentionally
    /// `Value` so each kind can choose its own delta projection without
    /// forcing a strongly typed enum here. Empty / missing means "the
    /// consumer must re-fetch the entity to know what changed".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delta: Option<Value>,
    /// Where the event came from. Lets the consumer attribute lag and
    /// drop duplicates from the second source.
    pub source: DashboardEventSource,
}

/// Tagged enum of supported dashboard event kinds. Tagged on `kind` so the
/// envelope flattens cleanly to JSON `{"kind": "...", "entity_id": ..., …}`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DashboardEventKind {
    /// A rulebook task was created, updated, archived, or deleted.
    /// `entity_id` is the task id (`phase11m_dashboard_push_cache`).
    #[serde(rename = "task.changed")]
    TaskChanged,
    /// A handoff file landed in `.rulebook/handoff/`.
    /// `entity_id` is the basename of the file.
    #[serde(rename = "handoff.appended")]
    HandoffAppended,
    /// A decision record changed (created or updated).
    /// `entity_id` is the decision id (e.g. `DEC-0042`).
    #[serde(rename = "decision.changed")]
    DecisionChanged,
    /// A new memory was persisted.
    /// `entity_id` is the memory id.
    #[serde(rename = "memory.appended")]
    MemoryAppended,
    /// A pattern or anti-pattern was added to the knowledge base.
    /// `entity_id` is the knowledge entry id.
    #[serde(rename = "knowledge.added")]
    KnowledgeAdded,
}

/// Publisher attribution. Mainly observability — the GUI does not switch
/// behavior on it, but operators want to know when the watcher path is
/// the only one carrying load (Synap unreachable scenario).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum DashboardEventSource {
    /// Emitted from inside the MCP tool handler that performed the write.
    Mcp,
    /// Emitted by the file-system watcher in `cortex-api`.
    Watcher,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn sample(kind: DashboardEventKind, entity_id: &str) -> DashboardEvent {
        DashboardEvent {
            event_id: "01J5XAMPLE0000000000000001".to_string(),
            kind,
            entity_id: entity_id.to_string(),
            summary: Some("status: pending → in-progress".to_string()),
            ts: "2026-05-02T23:45:00Z".to_string(),
            delta: Some(json!({ "status": "in-progress" })),
            source: DashboardEventSource::Mcp,
        }
    }

    fn round_trip(e: &DashboardEvent) -> DashboardEvent {
        let s = serde_json::to_string(e).expect("serialize");
        serde_json::from_str(&s).expect("deserialize")
    }

    #[test]
    fn task_changed_round_trips() {
        let e = sample(DashboardEventKind::TaskChanged, "phase11m_x");
        assert_eq!(round_trip(&e), e);
    }

    #[test]
    fn handoff_appended_round_trips() {
        let mut e = sample(DashboardEventKind::HandoffAppended, "_pending.md");
        e.delta = None;
        e.source = DashboardEventSource::Watcher;
        assert_eq!(round_trip(&e), e);
    }

    #[test]
    fn decision_changed_round_trips() {
        let e = sample(DashboardEventKind::DecisionChanged, "DEC-0042");
        assert_eq!(round_trip(&e), e);
    }

    #[test]
    fn memory_appended_round_trips() {
        let mut e = sample(DashboardEventKind::MemoryAppended, "01MEMORYULID");
        e.summary = None;
        assert_eq!(round_trip(&e), e);
    }

    #[test]
    fn knowledge_added_round_trips() {
        let e = sample(DashboardEventKind::KnowledgeAdded, "knowledge_42");
        assert_eq!(round_trip(&e), e);
    }

    #[test]
    fn kind_tag_is_dotted_in_json() {
        let e = sample(DashboardEventKind::TaskChanged, "phase11m_x");
        let v: Value = serde_json::from_str(&serde_json::to_string(&e).unwrap()).unwrap();
        assert_eq!(v["kind"], "task.changed");
        assert_eq!(v["entity_id"], "phase11m_x");
        assert_eq!(v["source"], "mcp");
    }

    #[test]
    fn omits_optional_fields_when_none() {
        let e = DashboardEvent {
            event_id: "01J5XAMPLE0000000000000002".to_string(),
            kind: DashboardEventKind::TaskChanged,
            entity_id: "phase11m_x".to_string(),
            summary: None,
            ts: "2026-05-02T23:45:00Z".to_string(),
            delta: None,
            source: DashboardEventSource::Watcher,
        };
        let v: Value = serde_json::from_str(&serde_json::to_string(&e).unwrap()).unwrap();
        assert!(v.get("summary").is_none());
        assert!(v.get("delta").is_none());
    }
}
